### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by paul-stubley** [jannikmi/timezonefinder#136]
This package looks great, just tried to install with:
`!pip install timezonefinder`
On a jupyter notebook kernal, tried both python2 and python3.

```
Collecting timezonefinder
  Downloading timezonefinder-4.2.0.tar.gz (38.1 MB)
     |████████████████████████████████| 38.1 MB 5.0 MB/s eta 0:00:01
    ERROR: Command errored out with exit status 1:
     command: /artifacts/virtualenv/python2/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4g6w0A/timezonefinder/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4g6w0A/timezonefinder/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-JbICGt
         cwd: /tmp/pip-install-4g6w0A/timezonefinder/
    Complete output (10 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4g6w0A/timezonefinder/setup.py", line 7, in <module>
        from timezonefinder.global_settings import DATA_FILE_NAMES
      File "timezonefinder/__init__.py", line 2, in <module>
        from .timezonefinder import TimezoneFinder
      File "timezonefinder/timezonefinder.py", line 276
        def closest_timezone_at(self, *, lat, lng, delta_degree=1, exact_computation=False, return_distances=False,
                                       ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by paul-stubley** [comment]
Fixed:

This was my misunderstanding of how to install a package into the current Jupyter notebooks. From Jupyter notebooks, 

use:

```
import sys
!{sys.executable} -m pip install timezonefinder
```

and not simply

```
!pip install timezonefinder
```

**Comment by jannikmi** [comment]
Hey Paul, is that how one should do it?
Or is there something that could be changed in this package to allow usual `pip install ...`?

**Comment by paul-stubley** [comment]
I've had difficulty `pip install`ing from inside notebooks before, I think it might be endemic of thinking you're operating and installing inside jupyters python instance but you're actually installing in your default python instance.  The first snippet above grabs your actual executable first, then uses that to install, so the new package turns up inside jupyter.
