### ISSUE TITLE
pip install timezonefinder fails on preparing metadata step

### ISSUE THREAD

**Issue by shil2** [jannikmi/timezonefinder#161]
Failed on python versions 3.9.13 and 3.10.6. Tried in a fresh conda environment and got this stacktrace:
```pip install timezonefinder
Collecting timezonefinder
  Downloading timezonefinder-6.1.3.tar.gz (45.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.7/45.7 MB 35.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Traceback (most recent call last):
        File "/Users/shil/miniconda3/envs/test/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/shil/miniconda3/envs/test/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/shil/miniconda3/envs/test/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/private/var/folders/2r/jwm9jt693wzdgyvlltwm8c1w0000gn/T/pip-build-env-qc7_6sie/overlay/lib/python3.10/site-packages/poetry/core/masonry/api.py", line 40, in prepare_metadata_for_build_wheel
          poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
        File "/private/var/folders/2r/jwm9jt693wzdgyvlltwm8c1w0000gn/T/pip-build-env-qc7_6sie/overlay/lib/python3.10/site-packages/poetry/core/factory.py", line 48, in create_poetry
          local_config = PyProjectTOML(path=poetry_file).poetry_config
        File "/private/var/folders/2r/jwm9jt693wzdgyvlltwm8c1w0000gn/T/pip-build-env-qc7_6sie/overlay/lib/python3.10/site-packages/poetry/core/pyproject/toml.py", line 74, in poetry_config
          assert isinstance(config, Table)
      AssertionError
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

**Comment by Lucianod28** [comment]
I had this issue too on ARM-based Ubuntu 22.04. Downgrading to 6.0.1 fixed it for me.

**Comment by shil2** [comment]
Install of timezonefinder-6.1.3 works fine today.. Not sure what happened.
