### ISSUE TITLE
`not enough values to unpack (expected 4, got 0)` in outside_the_boundaries_of

### ISSUE THREAD

**Issue by rez0n** [jannikmi/timezonefinder#209]
Hi, 
I faced with some rare issue in timezonefinder, it throwing `not enough values to unpack (expected 4, got 0)` exception randomly and rarely. I have no ideas about reproducing of this because I ran it for all coordinates in the database multiple times and have no luck to catch exception.
Submitting this report just in case if author have any ideas.

Timezonefinder version: 6.2.0
Python 3.11

Usage example:

```python
tf = TimezoneFinder()
tz = tf.timezone_at(lng=float(longitude), lat=float(latitude))
```

![CleanShot 2023-11-07 at 22 35 29@2x](https://github.com/jannikmi/timezonefinder/assets/725860/5b12ca9c-1d87-49fc-9c3e-27f9d571ab3d)

**Comment by jannikmi** [comment]
Thanks for reporting this. It would be best to unit test the respective functions for all possible values. Unfortunately I don't have enough time to implement this. Can anyone help?

**Comment by jannikmi** [comment]
Hello @rez0n, are you sure the error originates from the line in the screenshot?

**Comment by jannikmi** [comment]
I added unit tests for the highlighted functions. The tests are passing. Additional unit tests are required to rule out possible bugs.

@rez0n can you provide an example input to reproduce this? It seems very strange that the error cannot be reproduced even if you repeat your experiments. The code of timezonefinder should be deterministic, so it should either always or never throw an error for identical input.

**Comment by rez0n** [comment]
Hi @jannikmi 
Sorry for late response.

> are you sure the error originates from the line in the screenshot?

As you can see, it is Sentry.io report. It is always correct for me.

> can you provide an example input to reproduce this? 

Unfortunately no, as I said in the initial message I ran script for entire database and no any value did not triggered this error.
It is seems something very low level, maybe? On screenshot you can see `x` and `y` variables, maybe it is something what could help to debug this?

**Comment by kuanb** [comment]
Just chiming in that I am running into this now. In a running service I see the following logged:
```
cannot find timezone for: 120.347287,22.598127; ERROR: not enough values to unpack (expected 4, got 0)
```

When I run the same locally, it executes fine:
```
_coordinates = "120.347287,22.598127"

parsed_ll = [float(x) for x in _coordinates.split(",")]
tzid = TZ_FINDER.timezone_at(lng=parsed_ll[0], lat=parsed_ll[1])
assert tzid == 'Asia/Taipei'
```

Similar to the above poster, this occurs seemingly at random and is not reproducible locally. Will continue to investigate and report back here if I am able to discern further...

**Comment by jannikmi** [comment]
Thanks for reporting this!
Could you perhaps add small random noise to the floating point coordinates?

**Comment by chboe** [comment]
@kuanb did you figure out what the problem was? I am also facing this issue at random.

**Comment by jannikmi** [comment]
@chboe can you perhaps help to reproduce it and add some test cases?

**Comment by chboe** [comment]
@jannikmi It happens totally at random. Very odd behaviour. I tried adding some random noise and querying a second time. Will see if this solves my issue.

It doesn't even seem to be a boundary issue since all my test cases run very clearly inside timezone boundaries

**Comment by jannikmi** [comment]
Thanks for the report. 

And you encountered the error while running the query for statically defined test cases (coordinates)? That would inply that the behaviour of Timezonefinder is not deterministic, which would be very surprising for me.

**Comment by chboe** [comment]
Not well-defined test-cases but some code running in production that occasionally logged and error in datadog. When I then re-queryed with the same lat-lon it went fine - both in production and locally.

**Comment by jannikmi** [comment]
Might the different behaviour come from different floating point precisions?

**Comment by chboe** [comment]
My staging environment ran into the problem
`Traceback (most recent call last):
  File "/app/app/core/pv_estimation_methods/pv_lib.py", line 115, in estimator_method_pvlib
    pv_lib_pv_estimate = self.pv_lib_pv_estimate(location=location, weather_data=weather_data)
  File "/app/app/core/pv_estimation_methods/pv_lib.py", line 67, in pv_lib_pv_estimate
    tz=geocoder_controller.get_timezone(Coordinate(longitude=location.longitude, latitude=location.latitude))
  File "/app/app/core/geocoder.py", line 71, in get_timezone
    timezone_str = time_zone_finder.timezone_at(lng=coordinate.longitude, lat=coordinate.latitude)
  File "/usr/local/lib/python3.10/site-packages/timezonefinder/timezonefinder.py", line 447, in timezone_at
    if self.inside_of_polygon(poly_id, x, y):
  File "/usr/local/lib/python3.10/site-packages/timezonefinder/timezonefinder.py", line 388, in inside_of_polygon
    if self.outside_the_boundaries_of(poly_id, x, y):
  File "/usr/local/lib/python3.10/site-packages/timezonefinder/timezonefinder.py", line 378, in outside_the_boundaries_of
    xmax, xmin, ymax, ymin = self._fromfile(
ValueError: not enough values to unpack (expected 4, got 0)
`

I've recreated the code ran here with the exact coordinates that triggered this error and it runs fine.
Maybe this will help in some way.

`import datetime
from timezonefinder import timezonefinder
import pytz
time_zone_finder = timezonefinder.TimezoneFinder()

def get_timezone(lat, lon) -> datetime.tzinfo:
    timezone_str = time_zone_finder.timezone_at(lng=lon, lat=lat)
    if timezone_str is None:
        raise Exception(f"Could not determine timezone of coordinate: ({lat},{lon})")
    return pytz.timezone(timezone_str)

print(get_timezone(lat=56.142709, lon=9.171069))`
`Europe/Copenhagen

Process finished with exit code 0`

**Comment by ringsaturn** [comment]
If users face this issue, it's possible to make a minor change to capture what `_fromfile` actually returns.

From the example, we can see that 'in_memory' is False in the TimezoneFinder by default, so the data is [returned by NumPy](https://github.com/jannikmi/timezonefinder/blob/f886321f0cd71154216ddfcbd57ad4cf5247b499/timezonefinder/timezonefinder.py#L63-L78)'s [`fromfile`](https://numpy.org/doc/stable/reference/generated/numpy.fromfile.html).

I suggest adding these changes to [`get_polygon_boundaries`](https://github.com/jannikmi/timezonefinder/blob/6.5.0/timezonefinder/timezonefinder.py#L487-L496):

```diff
    def get_polygon_boundaries(self, poly_id: int) -> Tuple[int, int, int, int]:
        """returns the boundaries of the polygon = (lng_max, lng_min, lat_max, lat_min) converted to int32"""
        poly_max_values = getattr(self, POLY_MAX_VALUES)
        poly_max_values.seek(4 * NR_BYTES_I * poly_id)
-       xmax, xmin, ymax, ymin = self._fromfile(
+       file_result = self._fromfile(
            poly_max_values,
            dtype=DTYPE_FORMAT_SIGNED_I_NUMPY,
            count=4,
        )
+       xmax, xmin, ymax, ymin = file_result
        return xmax, xmin, ymax, ymin
```

Then we can get the `file_result` in platforms like Sentry.

Or inside `timezonefinder`, add a try/except to capture the results and add them to the exception messages.

---

The code inside NumPy's `fromfile` will be hard to debug: https://github.com/numpy/numpy/blob/6f428f2e0cbd2b809ce9ba76a531e01d6c983b9c/numpy/_core/records.py#L933-L939

**Comment by jannikmi** [comment]
Thanks for the suggestion. Could you open a PR with these changes?

**Comment by jannikmi** [comment]
@rez0n, @kuanb, @chboe, @ringsaturn in the lastest version `6.5.7` I improved the error handling and logging to catch the Value Error. Please update your `timezonefinder` version and report back when you hit this error again.

**Comment by jc2** [comment]
Hello, I have come across another very similar issue with this tool (detailed below).
![image](https://github.com/user-attachments/assets/7d198f16-a572-444a-86eb-b8f94f58a88a)

So far, the error behavior is very random, but I’ve been able to replicate it to some extent.
In my use case, I use TimezoneFinder as a singleton (because it’s very slow to load, around 0.6s). When I use concurrency with threads (sharing the singleton), It can trigger 4 or 5 errors for every 10,000 calls to the timezone_at function.
One way I’ve found to avoid the “unpack (expected 4, got 0)” issue is by using the in_memory=True option

**Comment by jannikmi** [comment]
@jc2 Thanks for sharing your experience.
Please note that the `Timezonefinder` instance should be used as a singleton, but is not thread safe!
I recommend using one individual instance per thread or share the instance safely by locking it with a semaphore.
